[env]
PORT = "8080"
HOST = "0.0.0.0"
ROOT_FOLDER = "/path/to/pitsu-root"
POSTGRES_USER = "postgres username"
POSTGRES_PASSWORD = "postgres password"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
POSTGRES_DB = "pitsu database name"
REMOTE_SEQ_API_KEY = "your-remote-seq-api-key"
LOCAL_SEQ_API_KEY = "your-local-seq-api-key"
SEQ_API_URL = "http://your-seq-server:5341"
SEQ_LOG_LEVEL = "warn"
PITSU_PUBLIC_URL = "http://your-pitsu-server:8080"
INVITE_CODE_SUFFIX = "your-invite-code-secret-end"
INVITE_CODE_PREFIX = "your-invite-code-secret-start"
INVITE_CODE_ENCRYPTION_KEY = "your-invite-code-encryption-key"
AWS_BUCKET_NAME = "your-s3-bucket-name"
AWS_REGION = "your-s3-region"
AWS_ACCESS_KEY_ID = "your-s3-access-key-id"
AWS_SECRET_ACCESS_KEY = "your-s3-secret-access-key"

# PITSU_API_KEY_PLACEHOLDER = "your-pitsu-api-key-placeholder"

VERSION_MAJOR = "0"
VERSION_MINOR = "0"
VERSION_PATCH = "0"

VERSION_HASH = "dev"
